server:
  port: 10000
spring:
  application:
    name: monolith-tues-ex

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(yQjR7rB+l+bE+9vLPcSpZNfxtQegBU5qBLSwtPlLdBHzNpE28tJq3btv6WMIIPP+28LomBkgZXbAA/KTLmT7ROnUlNpjDEuV7Uae1hDA1kS05x7SJKsKCD+/0E61ZIyp7cGNmc1FgJgmAeHLK4Q1M1V9+COjoKJB8/N/ewB9JmGeG1ZOxNz1PA6Msy1m1yMKxcDah9oa7Ow=)
    username: ENC(KL/vpOrra3OsvkoGO9VKnA==)
    password: ENC(fJ4mgRXE2KFNdt5riC0oYtG+LHA2Q4ex)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: aliyun.whoiszxl.com
    port: 6379
    password: ENC(HckT7CIUqeogjP/2PdYeU2a1MX9NvHM1)

jasypt:
  encryptor:
    password: whoiszxy #配置EncryptPropertiesUtils工具类里填写的秘钥，最好在命令行注入参数


jwt:
  config:
    key: whoiszxl
    ttl: 36000000

aliyun:
  sms:
    accessKeyId:
    accessKeySecret:
    template_code: SMS_99220057
    sign_name: zxlvoid验证码